// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://euxpbxpsxxpkmqcjmdxa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV1eHBieHBzeHhwa21xY2ptZHhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMzAzNzcsImV4cCI6MjA2NTkwNjM3N30.qc8GlcEA02xeKwtUPnOg4-OMPZ6Ya3z3iLqMtujHSUk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);